import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'parse_color.dart';

class AppColors {
  // static Color get whiteColor => parseColor("#fafafa");
  static Color get whiteColor => Colors.white;
  static Color get whiteColor1 => parseColor("#ede9f5");
  static Color get datePickerColor => parseColor("#9e9e9e");
  static Color get noRecordColor => parseColor("#757575");
  static const redColor = Colors.red;
  static Color get greenColor => parseColor("#008b00");
  static Color get tealColor800 => parseColor("#00695C");
  static Color get tealColor600 => parseColor("#00897B");
  static Color get orangeColorDark => parseColor("#ee6002");
  static Color get yellowColor => parseColor("#FFD600");
  static Color get lightBlack => parseColor("#5F636D");
  static Color get redColorShade => parseColor("#E57373");
  static Color get blueColorShade => parseColor("#42A5F5");
  static Color get greyColor800 => parseColor("#424242");
  static Color get greyColor700 => parseColor("#616161");
  static Color get greyColor600 => parseColor("#757575");
  static Color get greyColor400 => parseColor("#BDBDBD");
  static Color get greyColor500 => parseColor("#9E9E9E");
  static Color get greyColorLight => parseColor("#797979");
  static Color get greyColorLight1 => parseColor("#fbfafd");
  static Color get purpleColorLight1 => parseColor("#ede9f5");
  static Color get iconLightGreyColor => parseColor("#bcbcbc");
  static Color get lightPurple => parseColor("#f5f2fd");
  static Color get greyColorLight2 => parseColor("#bcbcbc");
  static Color get greyColorLight3 => parseColor("#f5f2fd");
  static Color get black1 => parseColor("#212121");
  static Color get blackColor => parseColor("#212121");
  static const blueColor = Colors.blue;
  static const greyColor = Colors.grey;
  static const purpleColor = Colors.deepPurple;
  static const transParentColor = Colors.transparent;
  static final primaryColor = Get.theme.primaryColor;
  static final primaryColorDark = Get.theme.primaryColorDark;
  static Color get blackColor100 => parseColor("#000000");
  static final Color counterIndicatorColor = parseColor("0xffff9800");
  static final Color blue900 = parseColor("0xFF0D47A1");
  static const blackColor54 = Colors.black54;
  static const blackColor45 = Colors.black45;
  static const blackColor87 = Colors.black87;
  static const blackColor38 = Colors.black38;
  static const greyColorShade500 = Colors.grey;
  static Color get orange400 => parseColor("#FFA726");
  static Color get green400 => parseColor("#66BB6A");
  static Color get red400 => parseColor("#EF5350");
  static Color get blueGrey400 => parseColor("#78909C");
  static Color get pink => parseColor("#ff3131");
}
